### ISSUE TITLE
Logo for Binge-Code

### ISSUE THREAD

**Issue by Master-Chief1** [Binge-Code/Algorithm-Visualizer#1]
We need a logo for the org Binge-Code. If anyone comes with some cool logo design, kindly add it to the img folder.

**Comment by MarkVed17** [comment]
![8bd081cf8be648e88acd8bb1659617ad](https://user-images.githubusercontent.com/59828215/86779481-40dca800-c079-11ea-9aa3-46aeca3af269.jpg)
